/**
 * Solar System physical and orbital data.
 *
 * Primary source: NASA Planetary Fact Sheet (metric),
 * NSSDC / NASA Goddard — https://nssdc.gsfc.nasa.gov/planetary/factsheet/
 *
 * Additional:
 * - Solar radius: IAU 2015 nominal solar radius (695 700 km)
 * - Solar mass: IAU 2015 GM_sun / G (1.9885e30 kg, rounded)
 * - Moon: NASA Moon Fact Sheet
 * - Moon counts change as new satellites are confirmed; values below
 *   follow the NASA fact sheets as commonly cited for education (2024).
 *
 * Do not duplicate these numbers elsewhere — import from this module.
 */
import type { BodyId, PlanetDefinition } from '../types/planet'

export const BODIES: readonly PlanetDefinition[] = [
  {
    id: 'sun',
    name: 'Güneş',
    englishName: 'Sun',
    category: 'star',
    radiusKm: 695_700,
    massKg: 1.9885e30,
    gravityMs2: 274,
    orbitalRadiusAu: 0,
    eccentricity: 0,
    inclinationDeg: 0,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 0,
    orbitalPeriodDays: 0,
    rotationPeriodHours: 609.12,
    axialTiltDeg: 7.25,
    moons: 0,
    meanTempC: 5500,
    atmosphere: 'Çoğunlukla hidrojen ve helyum. Güneş katı bir yüzey değil, sıcak bir plazma topudur.',
    color: '#F7C14A',
    description:
      'Güneş bir yıldızdır. Gezegenler onun etrafında döner.',
    facts: [
      'Güneş bir gezegen değil, bir yıldızdır. Kendi ışığını yapar.',
      'Güneş ateş değil, çok sıcak gazdır.',
      'Güneş’in ışığı Dünya’ya yaklaşık 8 dakika 20 saniyede gelir.',
    ],
  },
  {
    id: 'mercury',
    name: 'Merkür',
    englishName: 'Mercury',
    category: 'terrestrial',
    radiusKm: 2439.7,
    massKg: 3.301e23,
    gravityMs2: 3.7,
    orbitalRadiusAu: 0.387,
    eccentricity: 0.2056,
    inclinationDeg: 7.0,
    longitudeAscendingNodeDeg: 48.331,
    argumentPeriapsisDeg: 29.124,
    orbitalPeriodDays: 87.969,
    rotationPeriodHours: 1407.6,
    axialTiltDeg: 0.034,
    moons: 0,
    meanTempC: 167,
    atmosphere: 'Neredeyse yok. Gündüz çok ısınır, gece çok soğur.',
    color: '#A8A29E',
    description:
      'Merkür Güneş’e en yakın gezegendir. Küçüktür. Uydusu yoktur.',
    facts: [
      'Güneş’e en yakın gezegen Merkür’dür.',
      'Merkür’de bir gün, bir yıldan daha uzundur.',
      'Havası yok denecek kadar incedir. Isıyı tutamaz.',
    ],
  },
  {
    id: 'venus',
    name: 'Venüs',
    englishName: 'Venus',
    category: 'terrestrial',
    radiusKm: 6051.8,
    massKg: 4.867e24,
    gravityMs2: 8.87,
    orbitalRadiusAu: 0.723,
    eccentricity: 0.0068,
    inclinationDeg: 3.39,
    longitudeAscendingNodeDeg: 76.68,
    argumentPeriapsisDeg: 54.884,
    orbitalPeriodDays: 224.701,
    rotationPeriodHours: -5832.5,
    axialTiltDeg: 177.36,
    moons: 0,
    meanTempC: 464,
    atmosphere: 'Çok kalın karbondioksit. Isıyı tutar.',
    color: '#E8C07A',
    description:
      'Venüs en sıcak gezegendir. Dünya’ya benzer büyüklüktedir. Ters yönde döner.',
    facts: [
      'Güneş’e Merkür’den uzak olsa da Merkür’den sıcaktır.',
      'Kalın havası Güneş ısısını tutar.',
      'Ters döner; Güneş batıdan doğar gibi görünürdü.',
    ],
  },
  {
    id: 'earth',
    name: 'Dünya',
    englishName: 'Earth',
    category: 'terrestrial',
    radiusKm: 6371,
    massKg: 5.972e24,
    gravityMs2: 9.8,
    orbitalRadiusAu: 1.0,
    eccentricity: 0.0167,
    inclinationDeg: 0.00005,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 114.207,
    orbitalPeriodDays: 365.256,
    rotationPeriodHours: 23.934,
    axialTiltDeg: 23.44,
    moons: 1,
    meanTempC: 15,
    atmosphere: 'Azot ve oksijen. Canlıların nefes almasını sağlar.',
    color: '#3B82C4',
    description:
      'Dünya bizim evimizdir. Mavidir. Bir uydusu vardır: Ay.',
    facts: [
      'Gece ve gündüz, Dünya kendi etrafında döndüğü için olur.',
      'Yaz ve kış, Dünya biraz yana yatık durduğu için olur.',
      'Bir yılı Güneş etrafında 1 turdur (yaklaşık 365,25 gün).',
    ],
  },
  {
    id: 'moon',
    name: 'Ay',
    englishName: 'Moon',
    category: 'moon',
    parentId: 'earth',
    radiusKm: 1737.4,
    massKg: 7.342e22,
    gravityMs2: 1.62,
    orbitalRadiusAu: 0.00257,
    eccentricity: 0.0549,
    inclinationDeg: 5.145,
    longitudeAscendingNodeDeg: 125.08,
    argumentPeriapsisDeg: 318.15,
    orbitalPeriodDays: 27.322,
    rotationPeriodHours: 655.73,
    axialTiltDeg: 6.68,
    moons: 0,
    meanTempC: -20,
    atmosphere: 'Neredeyse yok.',
    color: '#C8C8CC',
    description:
      'Ay, Dünya’nın uydusudur. Güneş ışığını yansıtır.',
    facts: [
      'Ay kendi ışığını yapmaz; Güneş ışığını yansıtır.',
      'Dünya’dan hep aynı yüzü görünür. Dönmesi ile turu neredeyse aynı sürer.',
      'Ay’da çekim vardır; Dünya’dakinin yaklaşık altıda biridir.',
    ],
  },
  {
    id: 'mars',
    name: 'Mars',
    englishName: 'Mars',
    category: 'terrestrial',
    radiusKm: 3389.5,
    massKg: 6.417e23,
    gravityMs2: 3.71,
    orbitalRadiusAu: 1.524,
    eccentricity: 0.0934,
    inclinationDeg: 1.85,
    longitudeAscendingNodeDeg: 49.558,
    argumentPeriapsisDeg: 286.502,
    orbitalPeriodDays: 686.98,
    rotationPeriodHours: 24.623,
    axialTiltDeg: 25.19,
    moons: 2,
    meanTempC: -65,
    atmosphere: 'İnce karbondioksit. Dünya’daki gibi rahat nefes alınamaz.',
    color: '#C1440E',
    description:
      'Mars kırmızı gezegendir. Orada da mevsim vardır.',
    facts: [
      'Kırmızı rengi yüzeyindeki pastan gelir.',
      'İki küçük uydusu vardır: Phobos ve Deimos.',
      'Bir Mars günü Dünya gününe yakındır (yaklaşık 24,6 saat).',
    ],
  },
  {
    id: 'phobos',
    name: 'Phobos',
    englishName: 'Phobos',
    category: 'moon',
    parentId: 'mars',
    radiusKm: 11.27,
    massKg: 1.06e16,
    gravityMs2: 0.0057,
    orbitalRadiusAu: 6.267e-5,
    eccentricity: 0.0151,
    inclinationDeg: 1.093,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 0,
    orbitalPeriodDays: 0.3189,
    rotationPeriodHours: 7.65,
    axialTiltDeg: 0,
    moons: 0,
    meanTempC: -40,
    atmosphere: 'Neredeyse yok.',
    color: '#A89080',
    description: 'Phobos, Mars’ın iç uydusudur. Küçüktür ve gezegene çok yakındır.',
    facts: [
      'Phobos Mars’ın etrafında bir günden kısa tur atar.',
      'Yüzeyi engebeli ve karanlıktır; bir patates gibi şekilsizdir.',
      'Çekimi çok zayıftır; üzerinde durmak zordur.',
    ],
  },
  {
    id: 'deimos',
    name: 'Deimos',
    englishName: 'Deimos',
    category: 'moon',
    parentId: 'mars',
    radiusKm: 6.2,
    massKg: 1.5e15,
    gravityMs2: 0.003,
    orbitalRadiusAu: 1.568e-4,
    eccentricity: 0.00033,
    inclinationDeg: 0.93,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 0,
    orbitalPeriodDays: 1.263,
    rotationPeriodHours: 30.31,
    axialTiltDeg: 0,
    moons: 0,
    meanTempC: -40,
    atmosphere: 'Neredeyse yok.',
    color: '#B8A090',
    description: 'Deimos, Mars’ın dış uydusudur. Phobos’tan daha küçük ve daha uzaktır.',
    facts: [
      'Deimos, Mars’ın iki küçük uydusundan daha yavaş dolanır.',
      'Yüzeyi tozlu ve kraterlidir.',
      'İkisi de Dünya’nın Ay’ı kadar yuvarlak ve büyük değildir.',
    ],
  },
  {
    id: 'jupiter',
    name: 'Jüpiter',
    englishName: 'Jupiter',
    category: 'gasGiant',
    radiusKm: 69_911,
    massKg: 1.898e27,
    gravityMs2: 24.79,
    orbitalRadiusAu: 5.203,
    eccentricity: 0.0489,
    inclinationDeg: 1.3,
    longitudeAscendingNodeDeg: 100.464,
    argumentPeriapsisDeg: 273.867,
    orbitalPeriodDays: 4332.59,
    rotationPeriodHours: 9.925,
    axialTiltDeg: 3.13,
    moons: 95,
    meanTempC: -110,
    atmosphere: 'Hidrojen ve helyum. Katı bir yere ayak basılmaz.',
    color: '#D4A574',
    description:
      'Jüpiter en kocaman gezegendir. Çok hızlı döner. Çok uydusu vardır.',
    facts: [
      'Jüpiter bir gaz devidir; üzerinde yürünecek katı yer yoktur.',
      'Büyük olduğu için daha yükseğe zıplanmaz; çekimi Dünya’dan daha güçlüdür.',
      'Bir günü yaklaşık 10 saattir; çok hızlı döner.',
    ],
  },
  {
    id: 'io',
    name: 'Io',
    englishName: 'Io',
    category: 'moon',
    parentId: 'jupiter',
    radiusKm: 1821.6,
    massKg: 8.932e22,
    gravityMs2: 1.796,
    orbitalRadiusAu: 0.002819,
    eccentricity: 0.0041,
    inclinationDeg: 0.05,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 0,
    orbitalPeriodDays: 1.769,
    rotationPeriodHours: 42.456,
    axialTiltDeg: 0,
    moons: 0,
    meanTempC: -130,
    atmosphere: 'Çok ince; volkan gazları.',
    color: '#E8C86A',
    description: 'Io, Jüpiter’in volkanik uydusudur. Yüzeyi sarı-turuncu kükürtle kaplıdır.',
    facts: [
      'Güneş Sistemi’nin en volkanik dünyalarındandır.',
      'Jüpiter’in çekimi içini gerer; bu yüzden ısınır.',
      'Galile uydularının Jüpiter’e en yakın olanıdır.',
    ],
  },
  {
    id: 'europa',
    name: 'Europa',
    englishName: 'Europa',
    category: 'moon',
    parentId: 'jupiter',
    radiusKm: 1560.8,
    massKg: 4.8e22,
    gravityMs2: 1.315,
    orbitalRadiusAu: 0.004486,
    eccentricity: 0.009,
    inclinationDeg: 0.47,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 0,
    orbitalPeriodDays: 3.551,
    rotationPeriodHours: 85.2,
    axialTiltDeg: 0.1,
    moons: 0,
    meanTempC: -160,
    atmosphere: 'Neredeyse yok.',
    color: '#D8E4F0',
    description: 'Europa buzla kaplıdır. Buzun altında okyanus olabileceği düşünülür.',
    facts: [
      'Yüzeyi pürüzsüz buzdur; çizikler gibi çatlaklar vardır.',
      'Buzun altında tuzlu bir okyanus olabilir.',
      'Jüpiter’in dört büyük Galile uydusundan biridir.',
    ],
  },
  {
    id: 'ganymede',
    name: 'Ganimed',
    englishName: 'Ganymede',
    category: 'moon',
    parentId: 'jupiter',
    radiusKm: 2634.1,
    massKg: 1.482e23,
    gravityMs2: 1.428,
    orbitalRadiusAu: 0.007155,
    eccentricity: 0.0013,
    inclinationDeg: 0.2,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 0,
    orbitalPeriodDays: 7.155,
    rotationPeriodHours: 171.7,
    axialTiltDeg: 0.33,
    moons: 0,
    meanTempC: -163,
    atmosphere: 'Neredeyse yok.',
    color: '#B8A890',
    description: 'Ganimed, Güneş Sistemi’nin en büyük uydusudur. Merkür’den bile büyüktür.',
    facts: [
      'En büyük uydudur; bir gezegen kadar geniştir.',
      'Kendi manyetik alanı vardır.',
      'Jüpiter’in etrafında yaklaşık bir haftada tur atar.',
    ],
  },
  {
    id: 'callisto',
    name: 'Callisto',
    englishName: 'Callisto',
    category: 'moon',
    parentId: 'jupiter',
    radiusKm: 2410.3,
    massKg: 1.076e23,
    gravityMs2: 1.236,
    orbitalRadiusAu: 0.012585,
    eccentricity: 0.0074,
    inclinationDeg: 0.192,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 0,
    orbitalPeriodDays: 16.689,
    rotationPeriodHours: 400.5,
    axialTiltDeg: 0,
    moons: 0,
    meanTempC: -139,
    atmosphere: 'Neredeyse yok.',
    color: '#8A8078',
    description: 'Callisto, Galile uydularının en dışta olanıdır. Yüzeyi eski kraterlerle doludur.',
    facts: [
      'Dört büyük uydunun Jüpiter’den en uzağıdır.',
      'Yüzeyi Güneş Sistemi’ndeki en kraterli yerlerdendir.',
      'İçi Europa kadar ısınmaz; daha sakin durur.',
    ],
  },
  {
    id: 'saturn',
    name: 'Satürn',
    englishName: 'Saturn',
    category: 'gasGiant',
    radiusKm: 58_232,
    massKg: 5.683e26,
    gravityMs2: 10.44,
    orbitalRadiusAu: 9.537,
    eccentricity: 0.0565,
    inclinationDeg: 2.49,
    longitudeAscendingNodeDeg: 113.665,
    argumentPeriapsisDeg: 339.392,
    orbitalPeriodDays: 10_759.22,
    rotationPeriodHours: 10.656,
    axialTiltDeg: 26.73,
    moons: 146,
    meanTempC: -140,
    atmosphere: 'Hidrojen ve helyum.',
    color: '#E6D5A8',
    description:
      'Satürn’ün halkaları vardır. Halkalar buz ve kaya parçalarıdır.',
    facts: [
      'Halkalar bir tabak değil; buz, kaya ve toz parçalarıdır.',
      'Başka gezegenlerin de ince halkası vardır. Satürn’ünkü daha kolay görülür.',
      'En büyük uydusu Titan’dır.',
    ],
    hasRings: true,
    ringInnerScale: 1.22,
    ringOuterScale: 2.28,
  },
  {
    id: 'titan',
    name: 'Titan',
    englishName: 'Titan',
    category: 'moon',
    parentId: 'saturn',
    radiusKm: 2574.7,
    massKg: 1.3452e23,
    gravityMs2: 1.352,
    orbitalRadiusAu: 0.008168,
    eccentricity: 0.0288,
    inclinationDeg: 0.33,
    longitudeAscendingNodeDeg: 0,
    argumentPeriapsisDeg: 0,
    orbitalPeriodDays: 15.945,
    rotationPeriodHours: 382.68,
    axialTiltDeg: 0,
    moons: 0,
    meanTempC: -179,
    atmosphere: 'Kalın azot. Turuncu bir pus yüzeyi örter.',
    color: '#E0A060',
    description: 'Titan, Satürn’ün en büyük uydusudur. Kalın havası ve gölleri vardır.',
    facts: [
      'Güneş Sistemi’nde kalın havası olan tek uydudur.',
      'Yüzeyinde sıvı metan gölleri bulunur.',
      'Satürn’ün halkalarının dışında dolanır.',
    ],
  },
  {
    id: 'uranus',
    name: 'Uranüs',
    englishName: 'Uranus',
    category: 'iceGiant',
    radiusKm: 25_362,
    massKg: 8.681e25,
    gravityMs2: 8.69,
    orbitalRadiusAu: 19.191,
    eccentricity: 0.0457,
    inclinationDeg: 0.77,
    longitudeAscendingNodeDeg: 74.006,
    argumentPeriapsisDeg: 96.998,
    orbitalPeriodDays: 30_688.5,
    rotationPeriodHours: -17.24,
    axialTiltDeg: 97.77,
    moons: 28,
    meanTempC: -195,
    atmosphere: 'Hidrojen, helyum ve metan. Metan ona mavi-yeşil rengi verir.',
    color: '#7FDBDA',
    description:
      'Uranüs neredeyse yan yatarak döner. Bu yüzden mevsimleri gariptir.',
    facts: [
      'Uranüs neredeyse yan yatar. Yine de döner ve Güneş’in etrafında tur atar.',
      'Bu yüzden kutupları sırayla Güneş’e bakar.',
      'İnce halkaları da vardır.',
    ],
    hasRings: true,
    ringInnerScale: 1.55,
    ringOuterScale: 2.05,
  },
  {
    id: 'neptune',
    name: 'Neptün',
    englishName: 'Neptune',
    category: 'iceGiant',
    radiusKm: 24_622,
    massKg: 1.024e26,
    gravityMs2: 11.15,
    orbitalRadiusAu: 30.07,
    eccentricity: 0.0113,
    inclinationDeg: 1.77,
    longitudeAscendingNodeDeg: 131.784,
    argumentPeriapsisDeg: 276.336,
    orbitalPeriodDays: 60_182,
    rotationPeriodHours: 16.11,
    axialTiltDeg: 28.32,
    moons: 16,
    meanTempC: -200,
    atmosphere: 'Hidrojen, helyum ve metan. Güçlü rüzgârları vardır.',
    color: '#4166F5',
    description:
      'Neptün Güneş’ten en uzak gezegendir. Rüzgârları çok güçlüdür.',
    facts: [
      'Güneş Sistemi’nin en uzak gezegenidir.',
      'Rüzgârları çok hızlıdır.',
      'En büyük uydusu Triton’dur.',
      'İnce, soluk halkaları da vardır.',
    ],
    hasRings: true,
    ringInnerScale: 1.52,
    ringOuterScale: 1.78,
  },
  {
    id: 'pluto',
    name: 'Plüton',
    englishName: 'Pluto',
    category: 'dwarf',
    radiusKm: 1188.3,
    massKg: 1.303e22,
    gravityMs2: 0.62,
    orbitalRadiusAu: 39.482,
    eccentricity: 0.2488,
    inclinationDeg: 17.16,
    longitudeAscendingNodeDeg: 110.299,
    argumentPeriapsisDeg: 113.834,
    orbitalPeriodDays: 90_560,
    rotationPeriodHours: -153.29,
    axialTiltDeg: 122.53,
    moons: 5,
    meanTempC: -229,
    atmosphere: 'Çok ince; çoğu zaman donmuş azot ve metan.',
    color: '#C4A484',
    description:
      'Plüton çok küçük ve çok soğuktur. En büyük uydusu Kharon’dur.',
    facts: [
      'Plüton çok küçüktür. Güneş Sistemi’ni anlamamıza yardımcı olur.',
      'Güneş Sistemi Plüton’da bitmez. Daha ötede de gök cisimleri vardır.',
      'Yolu o kadar eğridir ki bazen Neptün’den Güneş’e daha yakın geçer.',
    ],
  },
]

const BY_ID = new Map(BODIES.map((body) => [body.id, body]))

export function getBody(id: BodyId): PlanetDefinition {
  const body = BY_ID.get(id)
  if (!body) {
    throw new Error(`Bilinmeyen gök cismi: ${id}`)
  }
  return body
}

export function getPlanets(): PlanetDefinition[] {
  return BODIES.filter((body) => body.category !== 'moon' && body.id !== 'sun')
}

export function getSelectableBodies(): PlanetDefinition[] {
  return [...BODIES]
}

export function getMoonsOf(parentId: BodyId): PlanetDefinition[] {
  return BODIES.filter((body) => body.parentId === parentId).slice().sort((a, b) => a.orbitalRadiusAu - b.orbitalRadiusAu)
}

/** Sun and planets in solar order, each followed by its classroom moons. */
export function bodiesInFamilyOrder(): PlanetDefinition[] {
  const ordered: PlanetDefinition[] = []
  for (const body of BODIES) {
    if (body.category === 'moon') continue
    ordered.push(body)
    ordered.push(...getMoonsOf(body.id))
  }
  return ordered
}

export function compareOptionLabel(body: PlanetDefinition): string {
  return body.category === 'moon' ? `- ${body.name}` : body.name
}
