import type { LabActivity, LabActivityId, LabRoomId } from '../types/lab'

export const LAB_ROOMS: { id: LabRoomId; title: string; blurb: string; tone: string }[] = [
  { id: 'motion', title: 'Hareket', blurb: 'Dönme, tur, yıl', tone: 'var(--amber)' },
  { id: 'earth', title: 'Dünya', blurb: 'Gece, gündüz, mevsim', tone: 'var(--cyan)' },
  { id: 'gravity', title: 'Yerçekimi', blurb: 'Düşme, ağırlık, zıplama', tone: '#ff8a5b' },
  { id: 'scale', title: 'Uzaklık', blurb: 'Boşluk, ısı, ışık', tone: '#b794f6' },
  { id: 'build', title: 'Sıra ve Ay', blurb: 'Diz, dolunay, tutulma', tone: '#f6e05e' },
  { id: 'sky', title: 'Gökyüzü', blurb: 'Yıldız, kepçe, kuyrukluyıldız', tone: '#7ee0ff' },
]

export const LAB_ACTIVITIES: LabActivity[] = [
  {
    id: 'earth-year',
    room: 'motion',
    title: 'Bir Dünya yılında kim tur atar?',
    question: 'Dünya Güneş etrafında 1 tur atınca Merkür ve Jüpiter ne yapar?',
    watchHint: '1 yılı izle. Merkür daha çok tur atar; Jüpiter turunu bitiremez.',
    choices: [
      { id: 'inner', label: 'Merkür daha çok tur atar' },
      { id: 'same', label: 'Hepsi aynı anda 1 tur atar' },
    ],
    simulateLabel: '1 yılı başlat',
    resultTitle: 'Merkür birkaç tur, Dünya 1 tur, Jüpiter turunu bitiremez.',
    explain: 'Güneş’e yakın gezegenin yılı kısadır. Bir Dünya yılında Merkür yaklaşık 4 tur atar.',
    uses3d: true,
  },
  {
    id: 'who-faster',
    room: 'motion',
    title: 'Kim önce tur atar?',
    question: 'Merkür mü, Dünya mı önce Güneş etrafında 1 turu bitirir?',
    watchHint: 'Yarışı başlat. Kim önce turunu bitirir?',
    choices: [
      { id: 'mercury', label: 'Merkür' },
      { id: 'earth', label: 'Dünya' },
      { id: 'same', label: 'Aynı anda' },
    ],
    simulateLabel: 'Yarışı başlat',
    resultTitle: 'Merkür turunu önce bitirdi.',
    explain: 'Merkür Güneş’e daha yakındır. Turu yaklaşık 88 gündür; Dünya’nınki 365 gün.',
    uses3d: true,
  },
  {
    id: 'spin-vs-orbit',
    room: 'motion',
    title: 'Dönme mi, tur mu?',
    question: 'Gece ve gündüz için Dünya ne yapmalı?',
    watchHint: 'Dönmeyi ve turu tek tek durdur. Gece hangisinde kaybolur?',
    choices: [
      { id: 'spin', label: 'Kendi etrafında dönmeli' },
      { id: 'orbit', label: 'Güneş etrafında tur atmalı' },
      { id: 'both', label: 'İkisi birden' },
    ],
    simulateLabel: 'Gördüm',
    resultTitle: 'Dönme gece-gündüz yapar, tur yıl yapar.',
    explain: 'Kendi etrafında dönünce gece ve gündüz olur. Güneş etrafında tur atınca yıl olur.',
    uses3d: true,
  },
  {
    id: 'day-night',
    room: 'earth',
    title: 'Gece ve gündüz nasıl olur?',
    question: 'İstanbul ve Diyarbakır geceye saatlerce ayrı mı girer?',
    watchHint: 'Camgöbeği İstanbul, amber Diyarbakır. Güneş bir tarafı ısıtır. Dünya dönünce gece yer değiştirir.',
    choices: [
      { id: 'same', label: 'Hayır, neredeyse birlikte' },
      { id: 'diff', label: 'Evet, saatlerce fark var' },
    ],
    simulateLabel: 'Gördüm',
    resultTitle: 'Aynı ülkede doğu ve batı neredeyse birlikte geceye girer.',
    explain: 'Aynı ülkede doğu ve batı neredeyse birlikte geceye girer. Amerika ile Türkiye gibi uzak yerler değil.',
    uses3d: true,
  },
  {
    id: 'mass-weight',
    room: 'gravity',
    title: 'Ay’da ben değişir miyim?',
    question: 'Ay’a gidince sen mi değişirsin, yoksa sadece daha mı hafif hissedersin?',
    watchHint: 'Kilonu seç. Üç yerde nasıl hissettiğine bak. Sen aynı çocuksun.',
    choices: [
      { id: 'yes', label: 'Ben değişirim' },
      { id: 'no', label: 'Ben aynıyım, orada çekim zayıf' },
    ],
    simulateLabel: 'Bunu gördüm',
    resultTitle: 'Sen aynı kalırsın. Ay’da daha hafif hissedersin.',
    explain: 'Sen aynı çocuksun. Ay’da çekim daha zayıf olduğu için daha hafif hissedersin.',
    uses3d: true,
  },
  {
    id: 'drop-ball',
    room: 'gravity',
    title: 'Aynı top nerede önce düşer?',
    question: 'Aynı top nerede önce yere düşer?',
    watchHint: 'Topları bırak. Aynı yükseklikten hangisi önce düşer?',
    choices: [
      { id: 'moon', label: 'Ay' },
      { id: 'earth', label: 'Dünya' },
      { id: 'jupiter', label: 'Jüpiter' },
    ],
    simulateLabel: 'Topları bırak',
    resultTitle: 'Jüpiter’de top daha çabuk düşer.',
    explain: 'Çekim güçlendikçe top daha çabuk düşer. Jüpiter’de en güçlü, Ay’da en yavaş.',
    uses3d: true,
  },
  {
    id: 'jump',
    room: 'gravity',
    title: 'Nerede daha yükseğe zıplarsın?',
    question: 'Nerede daha yükseğe zıplarsın?',
    watchHint: 'Bir yer seç, zıplat. Ay’da yüksek, Jüpiter’de alçak.',
    choices: [
      { id: 'moon', label: 'Ay' },
      { id: 'earth', label: 'Dünya' },
      { id: 'jupiter', label: 'Jüpiter' },
    ],
    simulateLabel: 'Zıplat',
    resultTitle: 'Ay’da zıplama daha yüksektir.',
    explain: 'Aynı zıplama Ay’da daha yükseğe çıkar, çünkü çekim daha zayıf. Jüpiter’de tersi.',
    uses3d: true,
  },
  {
    id: 'real-scale',
    room: 'scale',
    title: 'Gezegenler neden büyük çizilir?',
    question: 'Modellerde gezegenler neden bu kadar büyük gösterilir?',
    watchHint: 'Anlamak için büyüğü ve gerçek boşluğu karşılaştır.',
    choices: [
      { id: 'wrong', label: 'Çünkü gerçekte de öyle büyükler' },
      { id: 'model', label: 'Yoksa gezegenler görünmez olurdu' },
    ],
    simulateLabel: 'Bunu gördüm',
    resultTitle: 'Uzay çok boş. Küçük noktaları görelim diye büyütürüz.',
    explain: 'Gerçek boyutta gezegenler nokta kadar kalır. Sırayı görmek için onları büyütürüz.',
    uses3d: true,
  },
  {
    id: 'arrange-orbits',
    room: 'build',
    title: 'Gezegenleri diz',
    question: 'Güneş’ten uzağa doğru 8 gezegeni dizebilir misin?',
    watchHint: 'Önce adı seç. Sonra doğru halkaya dokun.',
    simulateLabel: 'Sırayı gördüm',
    resultTitle: 'Sıra hazır.',
    explain: 'Sıra, Güneş’e olan gerçek uzaklıktır. Merkür, Venüs, Dünya, Mars, Jüpiter, Satürn, Uranüs, Neptün.',
    uses3d: true,
  },
  {
    id: 'moon-phases',
    room: 'build',
    title: 'Dolunayı sen yap',
    question: 'Dolunay için Ay nerede olmalı?',
    watchHint: 'Ay’ı sürükle. Dolunay: Güneş, Dünya, Ay bir çizgide; Ay gece tarafında.',
    choices: [
      { id: 'night', label: 'Dünya’nın gece tarafında, Güneş–Dünya–Ay bir çizgide' },
      { id: 'between', label: 'Güneş ile Dünya’nın arasında' },
    ],
    simulateLabel: 'Ay’ı sürükle',
    resultTitle: 'Dolunayda Ay, Dünya’nın gece tarafındadır.',
    explain: 'Ay kendi ışığını yapmaz. Güneş ışığını yansıtır. Dolunayda Ay, Dünya’nın gece tarafındadır.',
    uses3d: true,
  },
  {
    id: 'stars-or-earth',
    room: 'sky',
    title: 'Yıldızlar mı kayıyor?',
    question: 'Gece yıldızlar mı yer değiştirir, Dünya mı döner?',
    watchHint: 'Önce gökyüzünün kayışına bak. Sonra Dünya’nın dönüşüne bak.',
    choices: [
      { id: 'stars', label: 'Yıldızlar yer değiştirir' },
      { id: 'earth', label: 'Dünya döner' },
    ],
    simulateLabel: 'Gördüm',
    resultTitle: 'Yıldızlar yerinde. Dünya döndüğü için gökyüzü kayıyor gibi durur.',
    explain: 'Yıldızlar bir gecede yer değiştirmez. Dünya döndüğü için gökyüzü kayıyor gibi görünür.',
    uses3d: true,
  },
  {
    id: 'star-names',
    room: 'sky',
    title: 'Bu hangi yıldız?',
    question: 'Kameranın baktığı yıldızı, rengine bakarak seç.',
    watchHint: 'Rengine ve kısa ipucuna bak, sonra adını seç.',
    simulateLabel: 'Yıldıza bak',
    resultTitle: 'Her yıldızın adı ve rengi ayrıdır.',
    explain: 'Her yıldızın adı ve rengi farklıdır. Tıklayınca kamera o yıldıza gider.',
    uses3d: true,
  },
  {
    id: 'space-mission',
    room: 'sky',
    title: 'Keşif yolu',
    question: 'Sırayla üç bakış: Mars, dolunay, Ay’da zıpla.',
    watchHint: 'Adımları sırayla gör. Atlamadan ilerle.',
    simulateLabel: 'Gördüm',
    resultTitle: 'Mars’ın yılı uzun. Dolunay bir çizgidir. Ay’da zıplama yüksektir.',
    explain: 'Mars’ın yılı Dünya’dan uzundur. Dolunay bir çizgidir. Ay’da çekim zayıf olduğu için zıplama yüksektir.',
    uses3d: true,
  },
  {
    id: 'light-travel',
    room: 'scale',
    title: 'Güneş ışığı anında mı gelir?',
    question: 'Güneş ışığı Dünya’ya anında mı gelir?',
    watchHint: 'Önce Dünya’ya, sonra Jüpiter’e ışık gönder. Hangisi daha uzun sürer?',
    choices: [
      { id: 'instant', label: 'Anında gelir' },
      { id: 'minutes', label: 'Birkaç dakikada gelir' },
    ],
    simulateLabel: 'Işığı gönder',
    resultTitle: 'Işık Dünya’ya yaklaşık 8 dakika 20 saniyede gelir.',
    explain: 'Işık çok hızlıdır ama Güneş çok uzaktır. Dünya’ya yaklaşık 8 dakika 20 saniyede gelir.',
    uses3d: true,
  },
  {
    id: 'seasons-tilt',
    room: 'earth',
    title: 'Yaz yakınlıktan mı?',
    question: 'Yaz, Dünya Güneş’e daha yakın olduğu için mi olur?',
    watchHint: 'Dünya dik dursun, sonra biraz yan dursun. Ocak ve temmuzu dene.',
    choices: [
      { id: 'closer', label: 'Evet, daha yakınız' },
      { id: 'tilt', label: 'Hayır, Dünya biraz yan durur' },
    ],
    simulateLabel: 'Bunu gördüm',
    resultTitle: 'Yaz yakınlıktan olmaz.',
    explain: 'Yaz, Dünya’nın biraz yan durmasından olur. Ocak’ta daha yakınız ama kuzeyde kıştır.',
    uses3d: true,
  },
  {
    id: 'closest-hottest',
    room: 'scale',
    title: 'En yakın en sıcak mı?',
    question: 'Hangisinin yüzeyi en sıcaktır?',
    watchHint: 'Venüs’ün kalın havasını kaldır ve geri koy. En sıcak yer değişir mi?',
    choices: [
      { id: 'mercury', label: 'Merkür' },
      { id: 'venus', label: 'Venüs' },
      { id: 'earth', label: 'Dünya' },
    ],
    simulateLabel: 'Sonucu gör',
    resultTitle: 'En yakın, en sıcak demek değildir. En sıcak yüzey Venüs’tür.',
    explain: 'Merkür Güneş’e en yakındır. Venüs’ün kalın havası ısıyı tutar. En sıcak yüzey Venüs’tür.',
    uses3d: true,
  },
  {
    id: 'comet-tail',
    room: 'sky',
    title: 'Kuyruk hep arkada mı?',
    question: 'Kuyruk hep arkada mı kalır?',
    watchHint: 'Sürükle veya yaklaştır: kuyruk Güneş’ten uzağa bakar.',
    choices: [
      { id: 'behind', label: 'Evet, hep arkada' },
      { id: 'sun', label: 'Hayır, Güneş’ten uzağa bakar' },
    ],
    simulateLabel: 'Gördüm',
    resultTitle: 'Kuyruk Güneş’ten kaçar.',
    explain: 'Kuyruk gidişin arkasında durmaz. Güneş onu kendinden uzağa iter.',
    uses3d: true,
  },
  {
    id: 'kepler-pizza',
    room: 'motion',
    title: 'Yakınken daha hızlı',
    question: 'Merkür Güneş’e yaklaşınca ne olur?',
    watchHint: 'Merkür halkasında kalsın. Güneş’e yaklaşınca sarı dilimde hızlanır; uzakta mavi dilimde yavaşlar.',
    choices: [
      { id: 'faster', label: 'Hızlanır' },
      { id: 'slower', label: 'Yavaşlar' },
      { id: 'same', label: 'Hep aynı hız' },
    ],
    simulateLabel: 'Gördüm',
    resultTitle: 'Güneş’e yakınken daha hızlı gider.',
    explain: 'Güneş’e yakınken daha hızlı gider. Uzaktayken yavaşlar. İki dilim aynı süredir.',
    uses3d: true,
  },
  {
    id: 'mercury-long-day',
    room: 'motion',
    title: 'Merkür’de gün mü uzun, yıl mı?',
    question: 'Merkür’de bir gün, bir yıldan kısa mıdır?',
    watchHint: 'Yılı izle. Tur biter, Güneş bir kez doğup batmaz.',
    choices: [
      { id: 'short', label: 'Evet, günü kısadır' },
      { id: 'long', label: 'Hayır, günü yıldan uzundur' },
    ],
    simulateLabel: '1 yılı izle',
    resultTitle: 'Yıl bitti, gün bitmedi.',
    explain: 'Merkür kendi etrafında çok yavaş döner. Yılı biter, Güneş bir kez doğup batmadan önce ikinci tura başlar.',
    uses3d: true,
  },
  {
    id: 'eclipse-align',
    room: 'build',
    title: 'Her dolunay tutulma mı?',
    question: 'Her dolunayda Ay kararır mı?',
    watchHint: 'Ay’ı sürükle. Tutulma için Dünya’nın gölgesine gir.',
    choices: [
      { id: 'always', label: 'Evet, her dolunay tutulmadır' },
      { id: 'align', label: 'Hayır, tam hiza ve gölge gerekir' },
    ],
    simulateLabel: 'Hizayı gördüm',
    resultTitle: 'Dolunay yetmez. Gölgeye girmek gerekir.',
    explain: 'Dolunay yetmez. Ay, Dünya’nın gölgesine tam girmelidir.',
    uses3d: true,
  },
  {
    id: 'ursa-hunt',
    room: 'sky',
    title: 'Kepçeyi bul',
    question: 'Kepçedeki yedi yıldızı bulabilir misin?',
    watchHint: 'Kepçedeki yedi parlak yıldıza dokun.',
    simulateLabel: 'Yıldızlara dokun',
    resultTitle: 'Büyükayı bir gezegen değil, yedi yıldızın kepçesidir.',
    explain: 'Büyükayı bir gezegen değil. Yedi parlak yıldızın gökyüzünde çizdiği kepçedir.',
    uses3d: true,
  },
  {
    id: 'light-diary',
    room: 'scale',
    title: 'Uzak ışık daha mı uzun gider?',
    question: 'Daha uzak bir yıldıza ışık daha mı uzun sürer?',
    watchHint: 'Önce Dünya’ya ışık gönder. Sonra Proxima yolunu izle.',
    choices: [
      { id: 'same', label: 'Hayır, her yere aynı anda varır' },
      { id: 'far', label: 'Evet, uzak yol daha uzun sürer' },
    ],
    simulateLabel: 'Karşılaştırdım',
    resultTitle: 'Işık Dünya’ya dakikalar, Proxima’ya yıllar sürer.',
    explain: 'Işık Dünya’ya dakikalar sürer. En yakın yıldıza (Proxima) dört yıldan uzun sürer.',
    uses3d: true,
  },
]

export function getActivity(id: LabActivityId): LabActivity {
  const found = LAB_ACTIVITIES.find((item) => item.id === id)
  if (!found) throw new Error(`Bilinmeyen simülasyon: ${id}`)
  return found
}

export function activitiesInRoom(room: LabRoomId): LabActivity[] {
  return LAB_ACTIVITIES.filter((item) => item.room === room)
}

export const CHALLENGE_IDS = ['arrange-orbits', 'moon-phases', 'closest-hottest', 'drop-ball', 'who-faster'] as const

export type ChallengeId = (typeof CHALLENGE_IDS)[number]

export const CHALLENGE_BLURB: Record<ChallengeId, string> = {
  'arrange-orbits': '8 gezegeni Güneş’ten uzağa diz.',
  'moon-phases': 'Ay’ı sürükle, dolunayı yakala.',
  'closest-hottest': 'En yakın mı, en sıcak mı?',
  'drop-ball': 'Aynı top nerede önce düşer?',
  'who-faster': 'Kim önce bir tur atar?',
}

export const CHALLENGE_VERB: Record<ChallengeId, string> = {
  'arrange-orbits': 'Diz',
  'moon-phases': 'Sürükle',
  'closest-hottest': 'Seç',
  'drop-ball': 'Seç',
  'who-faster': 'Seç',
}

export const CHALLENGE_ICON: Record<ChallengeId, 'planet' | 'orbit' | 'thermo' | 'weight'> = {
  'arrange-orbits': 'planet',
  'moon-phases': 'orbit',
  'closest-hottest': 'thermo',
  'drop-ball': 'weight',
  'who-faster': 'orbit',
}

export const CHALLENGE_ACTIVITIES = CHALLENGE_IDS.map((id) => getActivity(id))

export const FEATURED_ACTIVITIES = CHALLENGE_ACTIVITIES
