import { equatorialToSceneDir } from '../astronomy/skyCoordinates'
import type { Vec3 } from '../types/simulation'

export interface SkyWonder {
  id: string
  name: string
  tag: string
  fact: string
  kind: 'star' | 'rock'
}

function starDir(raHours: number, decDeg: number): Vec3 {
  return equatorialToSceneDir(raHours, decDeg)
}

export const NOTABLE_STARS: (SkyWonder & { x: number; y: number; z: number; color: string; size: number; raHours: number; decDeg: number })[] = [
  {
    id: 'sirius',
    name: 'Sirius',
    tag: 'En parlak',
    fact: 'Gece göğünün en parlak yıldızıdır. Işığı bize yaklaşık 8,6 yılda gelir.',
    kind: 'star',
    raHours: 6.7525,
    decDeg: -16.7161,
    ...starDir(6.7525, -16.7161),
    color: '#d7ecff',
    size: 2.6,
  },
  {
    id: 'proxima',
    name: 'Proxima Centauri',
    tag: 'En yakın',
    fact: 'Güneş’ten sonra bize en yakın yıldızdır. Işığı yaklaşık 4 yıl 3 ayda gelir.',
    kind: 'star',
    raHours: 14.6601,
    decDeg: -62.6794,
    ...starDir(14.6601, -62.6794),
    color: '#ffb080',
    size: 1.6,
  },
  {
    id: 'polaris',
    name: 'Polaris',
    tag: 'Kutup Yıldızı',
    fact: 'Kuzey yönünü gösterir. Gökyüzünde neredeyse yerinde durur.',
    kind: 'star',
    raHours: 2.5303,
    decDeg: 89.2641,
    ...starDir(2.5303, 89.2641),
    color: '#fff4d6',
    size: 2.1,
  },
  {
    id: 'betelgeuse',
    name: 'Betelgeuse',
    tag: 'Kırmızı büyük',
    fact: 'Orion’daki kırmızı büyük yıldızdır. Güneş’ten yüzlerce kat büyüktür.',
    kind: 'star',
    raHours: 5.9195,
    decDeg: 7.407,
    ...starDir(5.9195, 7.407),
    color: '#ff8a5b',
    size: 2.8,
  },
  {
    id: 'rigel',
    name: 'Rigel',
    tag: 'Mavi dev',
    fact: 'Orion’un ayağındaki mavi-beyaz büyük yıldızdır. Çok parlaktır.',
    kind: 'star',
    raHours: 5.2423,
    decDeg: -8.2016,
    ...starDir(5.2423, -8.2016),
    color: '#9fd4ff',
    size: 2.4,
  },
  {
    id: 'vycma',
    name: 'VY Canis Majoris',
    tag: 'Dev yıldız',
    fact: 'Bilinen en büyük yıldızlardan biridir. Güneş’in yerinde olsa Jüpiter’e kadar uzanırdı.',
    kind: 'star',
    raHours: 7.3849,
    decDeg: -25.7675,
    ...starDir(7.3849, -25.7675),
    color: '#ffd0a8',
    size: 3.1,
  },
  {
    id: 'earendel',
    name: 'Earendel',
    tag: 'En uzaklardan',
    fact: 'Bilinen en uzak yıldızlardan biridir. Işığı çok uzun yolda gelmiştir.',
    kind: 'star',
    raHours: 1.625,
    decDeg: -8.454,
    ...starDir(1.625, -8.454),
    color: '#f4e4ff',
    size: 1.8,
  },
  {
    id: 'vega',
    name: 'Vega',
    tag: 'Yaz üçgeni',
    fact: 'Kuzey göğünün en parlak yıldızlarındandır. Yaz üçgeninin bir köşesidir; ışığı yaklaşık 25 yılda gelir.',
    kind: 'star',
    raHours: 18.6156,
    decDeg: 38.7838,
    ...starDir(18.6156, 38.7838),
    color: '#b8d4ff',
    size: 2.2,
  },
  {
    id: 'arcturus',
    name: 'Arcturus',
    tag: 'Turuncu dev',
    fact: 'Kuzey göğünün en parlak yıldızıdır. Güneş’ten daha yaşlı, turuncu bir devdir.',
    kind: 'star',
    raHours: 14.261,
    decDeg: 19.1824,
    ...starDir(14.261, 19.1824),
    color: '#e8a060',
    size: 2.3,
  },
  {
    id: 'antares',
    name: 'Antares',
    tag: 'Akrep’in kalbi',
    fact: 'Akrep’teki kırmızı büyük yıldızdır. Rengi Mars’a benzer.',
    kind: 'star',
    raHours: 16.4901,
    decDeg: -26.432,
    ...starDir(16.4901, -26.432),
    color: '#d06048',
    size: 2.5,
  },
  {
    id: 'canopus',
    name: 'Canopus',
    tag: 'Güneyin parlakı',
    fact: 'Sirius’tan sonra göğün en parlak ikinci yıldızıdır. Güney yarımküreden daha kolay görülür.',
    kind: 'star',
    raHours: 6.3992,
    decDeg: -52.6957,
    ...starDir(6.3992, -52.6957),
    color: '#dce6ff',
    size: 2.5,
  },
  {
    id: 'deneb',
    name: 'Deneb',
    tag: 'Kuğu’nun kuyruğu',
    fact: 'Kuğu takımyıldızının kuyruğudur. Çok uzaktır; ışığı binlerce yılda gelir ama yine de parlak görünür.',
    kind: 'star',
    raHours: 20.6905,
    decDeg: 45.2803,
    ...starDir(20.6905, 45.2803),
    color: '#c8d8ff',
    size: 2.0,
  },
  {
    id: 'altair',
    name: 'Altair',
    tag: 'Kartal',
    fact: 'Yaz üçgeninin bir diğer köşesidir. Güneş’e Vega’dan daha yakındır; ışığı yaklaşık 17 yılda gelir.',
    kind: 'star',
    raHours: 19.8464,
    decDeg: 8.8683,
    ...starDir(19.8464, 8.8683),
    color: '#f0e0c8',
    size: 1.9,
  },
]

export const NAMED_ROCKS: (SkyWonder & { au: number; size: number; speed: number; tilt: number })[] = [
  {
    id: 'ceres',
    name: 'Ceres',
    tag: 'Çok küçük',
    fact: 'Taş kuşağının en iri cisimidir. Çok küçüktür. Üzerinde buz izleri vardır.',
    kind: 'rock',
    au: 2.77,
    size: 0.28,
    speed: 0.013,
    tilt: 0.12,
  },
  {
    id: 'vesta',
    name: 'Vesta',
    tag: 'Parlak asteroit',
    fact: 'Kuşaktaki en parlak asteroitlerden biridir. Bazen çıplak gözle görülebilir.',
    kind: 'rock',
    au: 2.36,
    size: 0.18,
    speed: 0.017,
    tilt: -0.08,
  },
  {
    id: 'pallas',
    name: 'Pallas',
    tag: 'Eğik yörünge',
    fact: 'Keşfedilen ikinci asteroittir. Yörüngesi diğerlerine göre daha eğiktir.',
    kind: 'rock',
    au: 2.77,
    size: 0.16,
    speed: 0.015,
    tilt: 0.34,
  },
]

export function findWonder(id: string | null): SkyWonder | undefined {
  if (!id) return undefined
  return NOTABLE_STARS.find((item) => item.id === id) ?? NAMED_ROCKS.find((item) => item.id === id)
}
