export interface SkyWonder {
  id: string
  name: string
  tag: string
  fact: string
  kind: 'star' | 'rock'
}

export const NOTABLE_STARS: (SkyWonder & { x: number; y: number; z: number; color: string; size: number })[] = [
  {
    id: 'sirius',
    name: 'Sirius',
    tag: 'En parlak',
    fact: 'Gece göğünün en parlak yıldızıdır. Güneş’ten daha sıcak ve daha parlaktır; ışığı bize yaklaşık 8,6 yılda gelir.',
    kind: 'star',
    x: 0.62,
    y: -0.12,
    z: 0.77,
    color: '#d7ecff',
    size: 2.6,
  },
  {
    id: 'proxima',
    name: 'Proxima Centauri',
    tag: 'En yakın',
    fact: 'Güneş’ten sonra bize en yakın yıldızdır. Işığı yaklaşık 4 yıl 3 ayda ulaşır. Çıplak gözle zor görünür.',
    kind: 'star',
    x: -0.42,
    y: -0.55,
    z: 0.72,
    color: '#ffb080',
    size: 1.6,
  },
  {
    id: 'polaris',
    name: 'Polaris',
    tag: 'Kutup Yıldızı',
    fact: 'Kuzey yönünü gösterir. Dünya’nın ekseni ona doğru baktığı için gökyüzünde neredeyse yerinde durur.',
    kind: 'star',
    x: 0.02,
    y: 0.98,
    z: 0.18,
    color: '#fff4d6',
    size: 2.1,
  },
  {
    id: 'betelgeuse',
    name: 'Betelgeuse',
    tag: 'Kırmızı üstdev',
    fact: 'Orion’daki kırmızı üstdevdir. Güneş’ten yüzlerce kat büyüktür; bir gün süpernova olabilir.',
    kind: 'star',
    x: 0.74,
    y: 0.16,
    z: 0.65,
    color: '#ff8a5b',
    size: 2.8,
  },
  {
    id: 'rigel',
    name: 'Rigel',
    tag: 'Mavi dev',
    fact: 'Orion’un ayağındaki mavi-beyaz devdir. Güneş’ten on binlerce kat daha parlaktır.',
    kind: 'star',
    x: 0.8,
    y: -0.18,
    z: 0.57,
    color: '#9fd4ff',
    size: 2.4,
  },
  {
    id: 'vycma',
    name: 'VY Canis Majoris',
    tag: 'Dev yıldız',
    fact: 'Bilinen en büyük yıldızlardan biridir. Güneş’in yerine konsaydı, yörüngesi Jüpiter’i geçerdi.',
    kind: 'star',
    x: -0.72,
    y: -0.28,
    z: 0.63,
    color: '#ffd0a8',
    size: 3.1,
  },
  {
    id: 'earendel',
    name: 'Earendel',
    tag: 'En uzaklardan',
    fact: 'Bilinen en uzak yıldız adaylarındandır. Işığı 12 milyar yıldan uzun yol almıştır; evrenin erken zamanına bakarız.',
    kind: 'star',
    x: -0.18,
    y: 0.42,
    z: -0.89,
    color: '#f4e4ff',
    size: 1.8,
  },
  {
    id: 'vega',
    name: 'Vega',
    tag: 'Yaz üçgeni',
    fact: 'Kuzey göğünün en parlak yıldızlarındandır. Yaz üçgeninin bir köşesidir; ışığı yaklaşık 25 yılda gelir.',
    kind: 'star',
    x: 0.12,
    y: 0.78,
    z: -0.61,
    color: '#b8d4ff',
    size: 2.2,
  },
  {
    id: 'arcturus',
    name: 'Arcturus',
    tag: 'Turuncu dev',
    fact: 'Kuzey göğünün en parlak yıldızıdır. Güneş’ten daha yaşlı, turuncu bir devdir.',
    kind: 'star',
    x: -0.55,
    y: 0.7,
    z: 0.45,
    color: '#e8a060',
    size: 2.3,
  },
  {
    id: 'antares',
    name: 'Antares',
    tag: 'Akrep’in kalbi',
    fact: 'Akrep takımyıldızındaki kırmızı üstdevdir. Rengi Mars’a benzer; adı “Mars’ın rakibi” anlamına gelir.',
    kind: 'star',
    x: -0.68,
    y: -0.35,
    z: -0.64,
    color: '#d06048',
    size: 2.5,
  },
  {
    id: 'canopus',
    name: 'Canopus',
    tag: 'Güneyin parlakı',
    fact: 'Sirius’tan sonra göğün en parlak ikinci yıldızıdır. Güney yarımküreden daha kolay görülür.',
    kind: 'star',
    x: 0.28,
    y: -0.88,
    z: 0.38,
    color: '#dce6ff',
    size: 2.5,
  },
  {
    id: 'deneb',
    name: 'Deneb',
    tag: 'Kuğu’nun kuyruğu',
    fact: 'Kuğu takımyıldızının kuyruğudur. Çok uzaktır; ışığı binlerce yılda gelir ama yine de parlak görünür.',
    kind: 'star',
    x: 0.48,
    y: 0.72,
    z: -0.5,
    color: '#c8d8ff',
    size: 2.0,
  },
  {
    id: 'altair',
    name: 'Altair',
    tag: 'Kartal',
    fact: 'Yaz üçgeninin bir diğer köşesidir. Güneş’e Vega’dan daha yakındır; ışığı yaklaşık 17 yılda gelir.',
    kind: 'star',
    x: 0.72,
    y: 0.22,
    z: -0.66,
    color: '#f0e0c8',
    size: 1.9,
  },
]

export const NAMED_ROCKS: (SkyWonder & { au: number; size: number; speed: number; tilt: number })[] = [
  {
    id: 'ceres',
    name: 'Ceres',
    tag: 'Cüce gezegen',
    fact: 'Asteroit kuşağının en iri cisimidir. Cüce gezegen sayılır; üzerinde buz ve tuz izleri bulunur.',
    kind: 'rock',
    au: 2.77,
    size: 0.28,
    speed: 0.013,
    tilt: 0.12,
  },
  {
    id: 'vesta',
    name: 'Vesta',
    tag: 'Parlak asteroit',
    fact: 'Kuşaktaki en parlak asteroitlerden biridir. Bazen çıplak gözle görülebilir.',
    kind: 'rock',
    au: 2.36,
    size: 0.18,
    speed: 0.017,
    tilt: -0.08,
  },
  {
    id: 'pallas',
    name: 'Pallas',
    tag: 'Eğik yörünge',
    fact: 'Keşfedilen ikinci asteroittir. Yörüngesi diğerlerine göre daha eğiktir.',
    kind: 'rock',
    au: 2.77,
    size: 0.16,
    speed: 0.015,
    tilt: 0.34,
  },
]

export function findWonder(id: string | null): SkyWonder | undefined {
  if (!id) return undefined
  return NOTABLE_STARS.find((item) => item.id === id) ?? NAMED_ROCKS.find((item) => item.id === id)
}
